name: Python
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-python-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download libraries
        uses: ./.github/composite-actions/download-libraries
        with:
          download-pybind: true
          download-googletest: false
      - name: Build pip package and test it
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cp test_input_data/WDC_satellites.csv src/python_bindings/
          cp test_input_data/TestLong.csv src/python_bindings/
          cp test_input_data/TestWide.csv src/python_bindings/
          cp test_input_data/transactional_data/rules-kaggle-rows.csv src/python_bindings/
          pip install .
          cd src/python_bindings
          python test_bindings.py
          cd ${{github.workspace}}
      - name: Test data stats
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          cp test_input_data/TestDataStats.csv src/python_bindings
          cd src/python_bindings
          python test_pybind_data_stats.py
